# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.

In [1]:
import torch
import numpy as np

# **Lists**

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

# **Numpy arrays**

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.23717229, 0.26913649, 0.78741468, 0.73027478],
       [0.19596412, 0.56426068, 0.76221497, 0.37396031],
       [0.12857089, 0.53343878, 0.382568  , 0.37325646]])

# **Tensors**

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.2693, -0.3604,  0.8877,  0.7403],
        [-0.4374,  0.8939,  0.9173,  1.3717],
        [-0.1585,  1.7911,  0.5584, -2.4298]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2372, 0.2691, 0.7874, 0.7303],
        [0.1960, 0.5643, 0.7622, 0.3740],
        [0.1286, 0.5334, 0.3826, 0.3733]], dtype=torch.float64)

In [11]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3 = my_torch3.view(2,5)
my_torch3

In [14]:
# Reshape if we don´t know number of items, use -1
my_torch2 = torch.arange(15)
my_torch2 = my_torch2.reshape(5,-1)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [16]:
my_torch2 = torch.arange(15)
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [4]:
#One change in tensor
my_torch5 = torch.arange(10)
my_torch6 = my_torch5.reshape(2,-1)

my_torch5[1]=4141
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [7]:
# Slices
my_torch7 = torch.arange(10)
my_torch7[7]

tensor(7)

In [9]:
my_torch8 = my_torch7.reshape(5,-1)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [13]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [12]:
my_torch8[:,1:].shape

torch.Size([5, 1])

### Tensor Maths Operations

In [14]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [15]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [16]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [17]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [18]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [19]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [20]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [21]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [22]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [23]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [24]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [25]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [26]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [27]:
# Reassignment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [28]:
tensor_a

tensor([1, 2, 3, 4])

In [29]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [30]:
tensor_a

tensor([ 6,  8, 10, 12])